@url = http://localhost:5000

###
GET {{url}}

##

@searchQuery = kghm

### Search quotes
# @name serach_quotes
GET {{url}}/quotes/search?query={{searchQuery}}
Content-Type: application/json


@symbol = EXPO
### Get quotes
# @name get_quotes
GET {{url}}/quotes?symbols={{symbol}}
Content-Type: application/json


@startDate = 2015-08-05T07:00:00-04
@endDate = 2015-08-05T07:00:00-04
### Get dividends
# @name get_dividends
GET {{url}}/quotes/dividends/{{symbol}}
Content-Type: application/json