@url = https://localhost:5000

###
GET {{url}}

##

@searchQuery = kghm

### Search quotes
# @name serach_quotes
GET {{url}}/quotes/search?query={{searchQuery}}
Content-Type: application/json


@symbol = EXPO
### Get quotes
# @name get_quotes
GET {{url}}/quotes?symbols={{symbol}}
Content-Type: application/json

@interval = 1d
@startDate = 2022-01-03T07:00:00-04
@endDate = 2023-01-03T07:00:00-04
### Get historical data by start and end date
# @name get_historical_data_by_start_and_end_date
GET {{url}}/quotes/historical-data/{{symbol}}?start={{startDate}}&end={{endDate}}&interval={{interval}}
Content-Type: application/json

@range = 1y
### Get historical data by range
# @name get_historical_data_by_range
GET {{url}}/quotes/historical-data/{{symbol}}?range={{range}}&interval={{interval}}
Content-Type: application/json

