version: '3'
name: stockfolio-dev

services:
  postgres:
    image: postgres:16
    container_name: postgres-dev
    shm_size: '4gb'
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: stockfolio@stockfolio.io
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5435:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes: 
      - redis:/data

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local
  redis:
    driver: local