version: '3'
name: stockfolio-dev

services:
  postgres:
    image: postgres:16
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: stockfolio@stockfolio.io
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "80"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local